---
- name: Create fluent-bit user
  user:
    name: "{{ fluentbit_user }}"
    shell: /usr/bin/false
    create_home: false

- name: Create fluent-bit directory
  file:
    path: /etc/fluent-bit
    state: directory
    owner: "{{ fluentbit_user }}"
    group: "{{ fluentbit_user }}"
    mode: '0755'

- name: Install fluent-bit on RHEL based system
  block:
    - name: Add fluent-bit repository
      yum_repository:
        name: fluent-bit
        description: Fluent-bit repo
        baseurl: "https://packages.fluentbit.io/almalinux/$releasever/"
        gpgcheck: no

    - name: Install fluent-bit package
      dnf:
        name: "fluent-bit"
        state: present
      notify: Restart Fluent-bit
  when: ansible_os_family == "RedHat"

- name: Create systemd service for fluent-bit
  copy:
    src: fluent-bit.service
    dest: /etc/systemd/system/fluent-bit.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Fluent-bit

- name: Create config file
  template:
    src: fluent-bit.conf.j2
    dest: /etc/fluent-bit/fluent-bit.conf
    owner: "{{ fluentbit_user }}"
    group: "{{ fluentbit_user }}"
  notify: Restart Fluent-bit
